# Module manifest for module 'chronometer'
# Generated by: Kevin Marquette
# Generated on: 2/2/2017

@{

# Script module or binary module file associated with this manifest.
RootModule = 'chronometer.psm1'

# Version number of this module.
ModuleVersion = '0.5.1'

# ID used to uniquely identify this module
GUID = 'f3719c3c-008a-4b25-b94d-fc9f587f62dd'

# Author of this module
Author = 'Kevin Marquette'

# Copyright statement for this module
Copyright = '(c) 2017 Kevin Marquette. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Performs a line by line measurement of execution times for scripts'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0'

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @('Get-Chronometer','Format-Chronometer')

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = @()

# Variables to export from this module
#VariablesToExport = '*'

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('analyzer','speed','measure','performance')

        # A URL to the license for this module.
        LicenseUri = 'https://github.com/KevinMarquette/Chronometer/blob/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/KevinMarquette/Chronometer'

    } # End of PSData hashtable

} # End of PrivateData hashtable
}

